#!/usr/bin/env python3
"""Generate the fixture for output naming of a nested leaf whose dotted path a top-level column takes.

Columns (three rows, one row group):
  a.b  int64             a top-level column literally named `a.b`: 1, null, 3
  a    struct<b: int64>  its field b dot-joins to `a.b` too: 10, 20, null

Flat output prints the top-level column as `a.b` and the nested field as `"a"."b"`, the quoted path that binds back
to it. Used by the scan unit tests and tests/lambda_integration.zig, and regenerated by tools/cli_smoke.sh, so every
caller exercises the same table.

Usage:  .venv/bin/python tools/gen_dotted_twin_fixture.py [OUT]   (default: ci/fixtures/parquet/dotted_twin.parquet)
"""

import pathlib
import sys

import pyarrow as pa
import pyarrow.parquet as pq

OUT = pathlib.Path(__file__).resolve().parent.parent / "ci" / "fixtures" / "parquet" / "dotted_twin.parquet"


def make_table() -> pa.Table:
    return pa.table({
        "a.b": pa.array([1, None, 3], pa.int64()),
        "a": pa.array([{"b": 10}, {"b": 20}, {"b": None}], pa.struct([("b", pa.int64())])),
    })


def main() -> None:
    out = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else OUT
    pq.write_table(make_table(), out, compression="NONE")
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
