const std = @import("std");

/// Metadata for a single column chunk within a row group.
pub const ColumnChunkMeta = struct {
    column_index: usize,
    /// Offset within the row group bytes
    relative_offset: u64,
    compressed_size: u64,
    uncompressed_size: u64,
    num_values: u64,
    /// File offset - calculated after all parts complete
    file_offset: u64 = 0,
};

/// Metadata for a single row group (morsel).
pub const RowGroupMeta = struct {
    row_group_index: usize,
    num_rows: u64,
    total_byte_size: u64,
    columns: std.ArrayListUnmanaged(ColumnChunkMeta),
    /// File offset - calculated after all parts complete
    file_offset: u64 = 0,

    pub fn deinit(self: *RowGroupMeta, allocator: std.mem.Allocator) void {
        self.columns.deinit(allocator);
    }
};

/// A unit of work generated by the compute engine to be written to S3.
/// Contains the encoded Parquet bytes and the metadata needed for the footer.
pub const Morsel = struct {
    /// Encrypted/Compressed Parquet bytes for this row group.
    /// The Sink takes ownership of this memory.
    data: []u8,

    /// Metadata for the footer.
    /// The Sink takes ownership of this metadata (and its internal allocations).
    meta: RowGroupMeta,

    pub fn deinit(self: *Morsel, allocator: std.mem.Allocator) void {
        allocator.free(self.data);
        self.meta.deinit(allocator);
    }
};
