[package]
name = "rust_bench"
version = "0.1.0"
edition = "2021"

[dependencies]
parquet = { version = "53.0.0", features = ["arrow", "async"] }
arrow = "53.0.0"
tokio = { version = "1", features = ["full"] }
object_store = { version = "0.10", features = ["aws"] }
futures = "0.3"

[[bin]]
name = "bench_s3"
path = "src/bench_s3.rs"
